# Generated by Django 3.2.7 on 2021-11-23 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='user_contact_info',
            field=models.OneToOneField(blank=True, help_text='Max 255 chars', max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_contactinfo', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
