# Generated by Django 3.2.7 on 2021-11-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='wishlist', to='product.ProductVersion', verbose_name='ProductWishlist'),
        ),
    ]
