# Generated by Django 3.2.7 on 2021-11-23 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0002_wishlist_product'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Max 255 chars', max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_wishlist', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='carts', to='product.ProductVersion', verbose_name='ProductCart'),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.checkoutbilling'),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Max 255 chars', max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_cart', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='checkoutbilling',
            name='user_billing_info',
            field=models.ForeignKey(blank=True, help_text='Max 255 chars', max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_checkout', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_item', to='order.shoppingcart'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_product', to='product.productversion'),
        ),
    ]
